java-solutions/m3-capstone/src/main/java/com/techelevator/npgeek/model/TemperatureScale.java
package com.techelevator.npgeek.model;

public class TemperatureScale {

	private boolean isCelsius = false;

	public boolean isCelsius() {
		return isCelsius;
	}

	public void setCelsius(boolean isCelsius) {
		this.isCelsius = isCelsius;
	}
	
	
}

java-solutions/m3-capstone/src/main/java/com/techelevator/npgeek/model/weather/Weather.java
package com.techelevator.npgeek.model.weather;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.techelevator.npgeek.model.TemperatureScale;

public class Weather {

	private int day;
	private int high;
	private int low;
	private String forecast;
	private TemperatureScale temperatureScale;
	
	public Weather(int day, int high, int low, String forcast, TemperatureScale temperatureScale) {
		this.day = day;
		this.high = high;
		this.low = low;
		this.forecast = forcast;
		this.temperatureScale = temperatureScale;
	}
		
	public int getHigh() {
		return getConvertedTemperature(high);
	}

	public int getLow() {
		return getConvertedTemperature(low);
	}
	
	public String getHighWithScale() {
		return getTempString(high);
	}
	
	public String getLowWithScale() {
		return getTempString(low);
	}
	
	public String getForecast() {
		return forecast;
	}

	public String getDayName() {
		if (day == 1) {
			return "Today";
		}
		if (day == 2) {
			return "Tomorrow";
		}
		LocalDate today = LocalDate.now();
		String dayName = today.plusDays(day - 1).getDayOfWeek().toString();
		return dayName.substring(0, 1) + dayName.substring(1).toLowerCase();
	}
	
	public List<String> getWarnings() {
		List<String> warnings = new ArrayList<String>();
		getForecastWarning(warnings);
		getTemperatureWarning(warnings);
		return warnings;
	}
	
	private void getForecastWarning(List<String> warnings) {
		
		
		switch (forecast.toLowerCase()) {
			case "snow":
				warnings.add("Pack snowshoes");
				break;
			case "rain":
				warnings.add("Wear weatherproof gear and shoes");
				break;
			case "thunderstorms":
				warnings.add("Seek shelter and avoid hiking on exposed ridges");
				break;
			case "sun":
				warnings.add("Pack sunblock");
				break;
		}

	}
	
	private void getTemperatureWarning(List<String> warnings) {
		if (high > 75) {
			warnings.add("High temperature: Bring extra water");
		}
		
		if (low < 20) {
			warnings.add("Frigid temperature: Danger from exposure");
		}
		
		if (Math.abs(high - low) > 20) {
			warnings.add("Varied temperature: Wear breathable layers");
		}
	}
	
	
	private boolean isCelius() {
		return temperatureScale.isCelsius();
	}
	
	private int getConvertedTemperature(int temp) {
		if (isCelius()) {
			return convertToCelius(temp);
		}
		return temp;
	}
	
	private int convertToCelius(int temp) {
		return (int) Math.round((temp - 32) * 5d/9d);
	}
	
	private String getTempString(int temp) {
		String temperatureString = String.valueOf(getConvertedTemperature(temp));
		if (isCelius()) {
			temperatureString += "C";
		} else {
			temperatureString += "F";
		}
		return temperatureString;
	}
}

java-solutions/m3-capstone/src/main/webapp/WEB-INF/jsp/parts/parkDetail-details.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/functions" prefix = "fn" %>

<div class="grid-container">
  <div class="ParkDescription"><c:out value="${park.parkDescription}" /></div>
  <div class="ParkName">
    <div class="Name gridParkName"><c:out value="${park.parkName}" /></div>
    <div class="StateFounded">
      <div class="State textState"><c:out value="${park.state}" /></div>
      <div class="Founded textRight">Founded <c:out value="${park.yearFounded}" /></div>
    </div>
  </div>
  <div class="VisitorInfo">
    <div class="campSitesTitle title">Campsites:</div>
    <div class="VisitorTitle title">Annual Visitors:</div>
    <div class="FeeTitle title">Entry Fee:</div>
    <div class="CampSitesCount"><c:out value="${park.numberOfCampsites}" /></div>
    <div class="VisitorCount"><c:out value="${park.annualVisitorCount}" /></div>
    <div class="EntryFee"><c:out value="${park.entryFee}" /></div>
  </div>
  <div class="ParkDetail">
    <div class="ClimateTitle title">Climate:</div>
    <div class="Climate"><c:out value="${park.climate}" /></div>
    <div class="AcerageTitle title">Acerage:</div>
    <div class="Acerage"><c:out value="${park.acreage}" /></div>
    <div class="milesTrailsTitle title">Miles of Trails:</div>
    <div class="milesOfTrails"><c:out value="${park.milesOfTrail}" /></div>
    <div class="elevationTitle title">Elevation:</div>
    <div class="elevation"><c:out value="${park.elevationInFeet}" />ft</div>
    <div class="animalsTitle title">Animal Species:</div>
    <div class="animalsCount"><c:out value="${park.numberOfAnimalSpecies}" /></div>
  </div>
  <div class="parkWeather">
	<c:import url="/WEB-INF/jsp/parts/parkDetail-weather.jsp" />
  </div>
</div>

java-solutions/m3-capstone/src/main/webapp/WEB-INF/jsp/parts/parkDetail-weather.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/functions" prefix = "fn" %>

<div class="scaleSwitch">
	<c:set var="otherScale" value="Celsius" />
	<c:if test="${temperatureScale.celsius == true}">
		<c:set var="otherScale" value="Farenheit" />
	</c:if>
	
	<c:url var="switchScaleUrl" value="/switchScale">
		<c:param name="parkCode" value="${park.parkCode}" />
		<c:param name="isCelsius" value="${!temperatureScale.celsius}" />
	</c:url>
	<a href="${switchScaleUrl}"><span><c:out value="Show in ${otherScale}" /></span></a>
	
</div>
<div class="parkWeatherMain">
	<c:forEach var="day" items="${weather.dailyWeather}" varStatus="iteration"> 
		<c:set var="weatherClass" value="weatherDay" />
		<c:if test="${iteration.index == 0 }">
			<c:set var="weatherClass" value="weatherToday" />
		</c:if>
		<div class="${weatherClass} weatherDisplay">
			<h3><c:out value="${day.dayName}" /></h3>
			<img src="<c:url value="img/weather/${fn:replace(day.forecast,' ', '')}.png" />" />
			<h4><c:out value="${day.forecast}" /></h4>
			<div class="tempContainer">
				<div class="temp tempHigh">
					<div class="tempTitle">High</div><div><c:out value="${day.highWithScale}" /></div>
				</div>
				<div class="temp tempLow">
					<div class="tempTitle">Low</div><div><c:out value="${day.lowWithScale}" /></div>
				</div>
			</div>
		
			<div class="warnings">
				<ul>
				<c:forEach var="warning" items="${day.warnings}">
					<li><c:out value="${warning}" /></li>
				</c:forEach>
				</ul>
			</div>
		</div>
	</c:forEach>
</div>